### ISSUE TITLE
support for `.env` files bundled in assets (needed for web support)

### ISSUE THREAD

**Issue by calvintam236** [frencojobs/envify#16]
Currently, it uses `dart:io` (no web support) to read the `.env` files.
https://github.com/frencojobs/envify/blob/efceeb56f8e20a5690d9b7ce0164153cb891cf55/envify_generator/lib/src/load_envs.dart#L14

During research for package, I was reading at [flutter_dotenv](https://pub.dev/packages/flutter_dotenv), and it allows to use `.env` files specified in `pubspec.yaml` under `assets`.

Will `Envify` include support using assets files? (I believe this is the only way for cross-platform build, such as web).

**Comment by frencojobs** [comment]
`dart:io` is used only in the generator package which is not really a dependency. The generator is meant to be used only locally (or during the build step on your VPS). It only generates a dart class that can be used independently of the platform or anything.

Plus, the reason I built envify is to point out the security flaw of that flutter_dotenv package. I have mentioned in README that storing (potentially important to not be exposed) credentials in a file is not safe.
