### ISSUE TITLE
update analyzer ^3.0.0

### ISSUE THREAD

**Issue by HudsonAfonso** [frencojobs/envify#22]
update analyzer ^3.0.0

**Comment by JEuler** [comment]
https://github.com/frencojobs/envify/pull/23

**Comment by davidAg9** [comment]
We need this ASAP please

**Comment by frencojobs** [comment]
Hey, Frenco here. Sorry for the trouble. This has been done. But I'm deprecating Envify in favor of [Envied](https://github.com/petercinibulk/envied). Envify will no longer receive further updates going forward. So I'd suggest migrating to Envied.
