### ISSUE TITLE
Envify does not work with Freezed

### ISSUE THREAD

**Issue by dorsamet** [frencojobs/envify#24]
Adding the two packages and running `flutter pub get` generates the following error:
```
Because envify_generator >=2.0.1 depends on analyzer ^2.0.0 and freezed 1.1.1 depends on analyzer ^3.0.0, envify_generator >=2.0.1 is incompatible with freezed 1.1.1.
And because no versions of freezed match >1.1.1 <2.0.0, envify_generator >=2.0.1 is incompatible with freezed ^1.1.1.
```

**Comment by frencojobs** [comment]
This has been fixed. But I'm deprecating Envify in favor of [Envied](https://github.com/petercinibulk/envied). Envify will no longer receive new updates going forward. Please migrate to Envied for new features and better support. Sorry for the trouble, and thank you for opening the issue.
