### ISSUE TITLE
envify analyser version

### ISSUE THREAD

**Issue by large** [frencojobs/envify#30]
```
Because no versions of build_runner match >2.3.3 <3.0.0 and build_runner 2.3.3 depends on analyzer >=4.4.0 <6.0.0, build_runner ^2.3.3 requires analyzer >=4.4.0 <6.0.0.
And because envify_generator >=2.0.1 depends on analyzer ^2.0.0, build_runner ^2.3.3 is incompatible with envify_generator >=2.0.1.
So, because yourapp depends on both envify_generator ^2.0.2 and build_runner ^2.3.3, version solving failed.
pub get failed (1; So, because spotprisen depends on both envify_generator ^2.0.2 and build_runner ^2.3.3, version solving failed.)
```

It is sad that this is not maintained any more, hopefully someone will update the analyzer version in the future @frencojobs 
Maybe let someone manage this package in the future?

**Comment by frencojobs** [comment]
Sorry for the trouble. Sdk and dependencies are now updated. But I'm deprecating Envify in favor of [Envied](https://github.com/petercinibulk/envied). I've put up a notice in README.md and I'll discontinue the package soon once the downloads have decreased. If you're still using Envify or still wanting to try it out, I'd suggest you to migrate to Envied already. Envify will no longer receive further updates.

Thank you and have a good day.
